image: node:latest

cache:
    paths:
        - node_modules/
        - .env
        - src/**/*.js
        - test/**/*.js

stages:
    - setup
    - build
    - test
    - deploy

setup:
    stage: setup
    script:
      - echo "Generating files and installing modules..."
      - npm run setup

build:
    stage: build
    script:
        - echo "Building Project..."
        - npm run build

test:
    stage: test
    script:
        - echo "Running test..."
        # - npm run build
        - npm run test

deploy:
    stage: deploy
    script:
      - echo "Deploying to heroku..."
      - git push heroku develop
