image: node:latest

stages:
    - build
    - test
    - deploy
    - deploy_dev
    - deploy_prod

build:
    stage: build
    before_script:
        - npm run setup
    script:
        - echo "Building Project..."
        - npm run build
    artifacts:
        paths:
            - src/
            - test/
        expire_in: 1 day
    cache:
        paths:
            - node_modules/
            - .env

test:
    stage: test
    script:
        - echo "Running test..."
        - npm run test

deploy_production:
    stage: deploy_prod
    before_script:
        - git config user.email "maxdevos@iastate.edu"
        - git config user.name "GitLab CI on behalf of Maxwell DeVos"
    script:
        - git checkout $CI_COMMIT_REF_NAME
        - git commit --allow-empty -m "Publish to Heroku at $(date)"
        - git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/prod-cs319.git $CI_COMMIT_REF_NAME:master
    only:
        - tags

deploy_development:
    stage: deploy_dev
    before_script:
        - git config user.email "maxdevos@iastate.edu"
        - git config user.name "GitLab CI on behalf of Maxwell DeVos"
    script:
        - git checkout $CI_COMMIT_REF_NAME
        - git commit --allow-empty -m "Publish to Heroku at $(date)"
        - git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/dev-cs319.git $CI_COMMIT_REF_NAME:master
    only:
        - develop

deploy_stage:
    stage: deploy
    before_script:
        - git config user.email "maxdevos@iastate.edu"
        - git config user.name "GitLab CI on behalf of Maxwell DeVos"
    script:
        - git checkout $CI_COMMIT_REF_NAME
        - git commit --allow-empty -m "Publish to Heroku at $(date)"
        - git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/staging-cs319.git $CI_COMMIT_REF_NAME:master