image: node:10.15.0

cache:
    paths:
        - node_modules/
        -.env

stages:
    - setup
    - build
    - test

setup:
    stage: setup
    script:
      - echo "Generating files and installing modules..."
      - npm setup

build:
    stage: build
    script:
        - echo "Building Project..."
        - npm run build

test:
    stage: test
    script:
        - echo "Running test..."
        - npm run test
