image: node:latest

cache:
    paths:
        - node_modules/
        - .env

stages:
    - build
    - test
    - deploy

before_script:
    - echo "Generating files and installing modules..."
    - npm run setup

build:
    stage: build
    script:
        - echo "Building Project..."
        - npm run build
    artifacts:
        paths:
            - src/**/*.js
            - test/**/*.js
        expire_in: 1 week

test:
    stage: test
    script:
        - echo "Running test..."
        # - npm run build
        - npm run test

deploy:
    stage: deploy
    script:
        - echo "Deploying to heroku..."
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
        - dpl --provider=heroku --app="cs319-group-project" --api-key=$HEROKU_API_KEY
