image: node:latest

cache:
    paths:
        - node_modules/
        - .env

stages:
    - build
    - test
    - deploy

build:
    stage: build
    before_script:
        - npm run setup
    script:
        - echo "Building Project..."
        - npm run build
    artifacts:
        paths:
            - src/
            - test/
        expire_in: 1 week

test:
    stage: test
    script:
        - echo "Running test..."
        - npm run test

deploy_development:
    stage: deploy
    # before_script:
    #     - git config user.email "maxdevos@iastate.edu"
    #     - git config user.name "GitLab CI on behalf of Maxwell DeVos"
    script:
        - git commit --allow-empty -m "Publish to Heroku at $(date)"
        - git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/dev-cs319.git $CI_COMMIT_REF_NAME:master
    # before_script:
    #     - apt-get update -qy
    #     - apt-get install -y ruby-dev
    #     - gem install dpl
#   only:
#   - develop

# deploy_production:
#     stage: deploy
#     before_script:
#         - apt-get update -qy
#         - apt-get install -y ruby-dev
#         - gem install dpl
#     script:
#         - echo "Deploying to heroku..."
#         - dpl --provider=heroku --app="prod-cs319" --api-key=$HEROKU_API_KEY
#   only:
#   - master

#   deploy_stage:
#     stage: deploy
#     before_script:
#         - apt-get update -qy
#         - apt-get install -y ruby-dev
#         - gem install dpl
#     script:
#         - echo "Deploying to heroku..."
#         - dpl --provider=heroku --app="staging-cs319" --api-key=$HEROKU_API_KEY