image: node:latest

cache:
    paths:
        - node_modules/
        - .env

stages:
    - build
    - test
    - deploy

build:
    stage: build
    before_script:
        - npm run setup
    script:
        - echo "Building Project..."
        - npm run build
    artifacts:
        paths:
            - src/
            - test/
        expire_in: 1 week

test:
    stage: test
    script:
        - echo "Running test..."
        - npm run test

deploy:
    stage: deploy
    before_script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
    script:
        - echo "Deploying to heroku..."
        - dpl --provider=heroku --app="cs319-group-project" --api-key=$HEROKU_API_KEY
